title: "Soukeye Thiam"
logo: img/WhatsApp Image 2026-03-17 at 23.13.17.jpeg
description: "Portfolio Data scientist - IA, Data Science, Formation"
show_doawnload: true
theme: jekyll-theme-minimal
lang: fr
